apiVersion: v1
kind: Pod
metadata:
  name: efs-monitor
  labels:
    name: efs-monitor
spec:
  containers:
  - name: efs-monitor
    image: ${EFS_MONITOR_IMAGE}
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
  #   volumeMounts:
  #     - name: ec2-volume
  #       mountPath: ${DIRECTORY_TO_WATCH}
  # volumes:
  # - name: ec2-volume
  #   persistentVolumeClaim:
  #     claimName: claim-nfs-monitor-app
