
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: ${DATABASE_NAME}
            - name: POSTGRES_USER
              value: ${DATABASE_USER}
            - name: POSTGRES_PASSWORD
              value: ${DATABASE_PASSWORD}
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "250Mi"
              cpu: "150m"
          volumeMounts:
            - name: postgres-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: claim-nfs-postgres
         