FROM python:3.12-alpine3.21

RUN mkdir -p /app ${DIRECTORY_TO_WATCH} && \
    pip install --upgrade pip && \
    pip install --no-cache-dir django watchdog 

WORKDIR /app 

COPY monitor.py  /app/

CMD [ "python3.12","monitor.py"]

