FROM nginx:latest

# Crear los directorios necesarios
RUN mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled

COPY streaming_project /etc/nginx/sites-available/streaming_project

RUN ln -s /etc/nginx/sites-available/streaming_project /etc/nginx/sites-enabled/

CMD [ "/usr/sbin/nginx", "-g", "daemon off;" ]