FROM nginx:latest

# Crear los directorios necesarios
RUN mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled /etc/nginx/certs

COPY streaming_project fullchain.pem privkey.pem /etc/nginx/certs/

RUN mv /etc/nginx/certs/streaming_project /etc/nginx/sites-available && \ 
    ln -s /etc/nginx/sites-available/streaming_project /etc/nginx/sites-enabled/

CMD [ "/usr/sbin/nginx", "-g", "daemon off;" ]