apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-monitor
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
  csi:
    driver: efs.csi.aws.com
    volumeHandle: ${efs_id}
