apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-efs
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: ${efs_id}
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/terraform/efs"
reclaimPolicy: Retain
mountOptions:
  - tls
volumeBindingMode: Immediate