apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitor-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-nfs
  nfs:
    server: "${nfs_server_ip}"        # IP privada de EC2 NFS
    path: /srv/nfs/kubedata/monitor
    readOnly: false