apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitor-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${nfs_server_ip}"        # IP privada de EC2 NFS
    path: /srv/nfs/kubedata/media