apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-nfs
  mountOptions:
    - nolock
  nfs:
    server: ${nfs_server_ip}
    path: /srv/nfs/kubedata/static