apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claimefs-monitor-app
spec:
  accessModes:
    - ReadWriteMany
  volumeName: efs-pv
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi