apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-web-server
spec:
  accessModes:
    - ReadWriteMany
  volumeName: web-server-pv
  storageClassName: manual-nfs
  resources:
    requests:
      storage: 20Gi