apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-s3-postgres
spec:
  accessModes:
    - ReadWriteMany
  volumeName: postgres-pv
  storageClassName: manual-nfs
  resources:
    requests:
      storage: 20Gi