apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-s3-postgres
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: s3-storage-class
  resources:
    requests:
      storage: 20Gi