apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeName: efs-pv-postgres
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi