# Generated by Django 5.1.7 on 2025-03-16 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Materia',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='allowed_categories',
            new_name='allowed_materia',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='category',
            new_name='materia',
        ),
    ]
