# Generated by Django 5.1.7 on 2025-03-16 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_rename_category_materia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='allowed_materia',
            new_name='allowed_materias',
        ),
    ]
