# Generated by Django 5.1.7 on 2025-03-16 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0007_uservideoprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVideoProgress',
        ),
    ]
